var canvas = document.createElement('canvas');
canvas.width = 250;
canvas.height = 250;
canvas.id = '123';
document.body.appendChild(canvas);
var step = 6;
var canvas = document.getElementById('123');
var ctx = canvas.getContext('2d');
canvas.height = 500;
canvas.width = 500;
canvas.style.left = '900px';
canvas.style.top = '200px';
canvas.style.position = "absolute";
var rad;
ctx.beginPath();
step = 6;
rad = 9;
ctx.moveTo(canvas.width / 2, canvas.height / 2 - step * rad / 2);
ctx.lineTo(canvas.width / 2 + step * rad, canvas.height / 2);
ctx.lineTo(canvas.width / 2, canvas.height / 2);
ctx.fillStyle = '#5376c2';
ctx.fill();
ctx.fillRect(canvas.width / 2 - step * rad, canvas.height / 2 - step * rad, step * rad, step * rad);
ctx.arc(canvas.width / 2, canvas.height / 2, rad * step, Math.PI, Math.PI / 2, true);
ctx.fillStyle = '5376c2';
ctx.fill();
ctx.beginPath();
ctx.moveTo(canvas.width / 2, 0);
ctx.lineTo(canvas.width / 2, canvas.height);
ctx.moveTo(canvas.width / 2, 0);
ctx.lineTo(canvas.width / 2 + 7, 10);
ctx.moveTo(canvas.width / 2, 0);
ctx.lineTo(canvas.width / 2 - 7, 10);
ctx.moveTo(0, canvas.height / 2);
ctx.lineTo(canvas.width, canvas.height / 2);
ctx.moveTo(canvas.width, canvas.height / 2);
ctx.lineTo(canvas.width - 10, canvas.height / 2 - 7);
ctx.moveTo(canvas.width, canvas.height / 2);
ctx.lineTo(canvas.width - 10, canvas.height / 2 + 7);
ctx.stroke();
ctx.closePath();
ctx.beginPath();
ctx.fillStyle = 'black';
ctx.font = 'Bold 13px Consolas';
ctx.moveTo(canvas.width / 2 + rad * step, canvas.height / 2);
ctx.lineTo(canvas.width / 2 + rad * step, canvas.height / 2 + 5);
ctx.lineTo(canvas.width / 2 + rad * step, canvas.height / 2 - 5);
ctx.fillText(rad, canvas.width / 2 + rad * step, canvas.height / 2 - 12);
ctx.moveTo(canvas.width / 2 + rad / 2 * step, canvas.height / 2);
ctx.lineTo(canvas.width / 2 + rad / 2 * step, canvas.height / 2 + 5);
ctx.lineTo(canvas.width / 2 + rad / 2 * step, canvas.height / 2 - 5);
ctx.fillText(rad / 2, canvas.width / 2 + rad / 2 * step, canvas.height / 2 - 12);
ctx.moveTo(canvas.width / 2 - rad * step, canvas.height / 2);
ctx.lineTo(canvas.width / 2 - rad * step, canvas.height / 2 + 5);
ctx.lineTo(canvas.width / 2 - rad * step, canvas.height / 2 - 5);
ctx.fillText('-' + rad, canvas.width / 2 - rad * step, canvas.height / 2 - 12);
ctx.moveTo(canvas.width / 2 - rad / 2 * step, canvas.height / 2);
ctx.lineTo(canvas.width / 2 - rad / 2 * step, canvas.height / 2 + 5);
ctx.lineTo(canvas.width / 2 - rad / 2 * step, canvas.height / 2 - 5);
ctx.fillText('-' + rad / 2, canvas.width / 2 - rad / 2 * step, canvas.height / 2 - 12);
ctx.moveTo(canvas.width / 2, canvas.height / 2 - rad * step);
ctx.lineTo(canvas.width / 2 + 5, canvas.height / 2 - rad * step);
ctx.lineTo(canvas.width / 2 - 5, canvas.height / 2 - rad * step);
ctx.fillText(rad, canvas.width / 2 + 10, canvas.height / 2 - rad * step);
ctx.moveTo(canvas.width / 2, canvas.height / 2 - rad / 2 * step);
ctx.lineTo(canvas.width / 2 + 5, canvas.height / 2 - rad / 2 * step);
ctx.lineTo(canvas.width / 2 - 5, canvas.height / 2 - rad / 2 * step);
ctx.fillText(rad / 2, canvas.width / 2 + 10, canvas.height / 2 - rad / 2 * step);
ctx.moveTo(canvas.width / 2, canvas.height / 2 + rad * step);
ctx.lineTo(canvas.width / 2 + 5, canvas.height / 2 + rad * step);
ctx.lineTo(canvas.width / 2 - 5, canvas.height / 2 + rad * step);
ctx.fillText('-' + rad, canvas.width / 2 + 10, canvas.height / 2 + rad * step);
ctx.moveTo(canvas.width / 2, canvas.height / 2 + rad / 2 * step);
ctx.lineTo(canvas.width / 2 + 5, canvas.height / 2 + rad / 2 * step);
ctx.lineTo(canvas.width / 2 - 5, canvas.height / 2 + rad / 2 * step);
ctx.fillText('-' + rad / 2, canvas.width / 2 + 10, canvas.height / 2 + rad / 2 * step);
ctx.fillText('y', canvas.width / 2 + 10, 10);
ctx.fillText('x', canvas.width, canvas.height / 2 - 10);
ctx.stroke();